name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: "@kabinet/event-sdk"

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          scope: '@kabinet'

      - name: Install, Build & Publish
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm ci
          npm run build
          npm pack --dry-run
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}